### ISSUE TITLE
Propose network persistence

### ISSUE THREAD

**Issue by killtheliterate** [Denver-Devs/heliograph#6]
We need to get in writing how we would like to persist the peer-to-peer network, given users can join and leave the network. We want to maintain the least amount of information about the fewest number of people on the server (the Super Peer).

**Comment by talon** [comment]
Opened up the Friends `package.json` found probably the two most relevant modules to us.

https://github.com/mafintosh/signalhub
https://www.npmjs.com/package/webrtc-swarm

**Comment by talon** [comment]
I think we could prototype with that and if/when we run into limitations grok the implementation and modify whevs. This would mean, I think, we just use signalhub as the server. And then create `heliograph-swarm` which has signalhub IPs to connect to. Just like how 'friends-swarm' does it.

**Comment by talon** [comment]
## Swarm Interface Proposal:

https://github.com/Denver-Devs/heliograph-swarm/pull/1

Server is just the `signalhub` module
https://github.com/mafintosh/signalhub
